In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
my_df = pd.DataFrame({"A" : [1,4,7,10,13],
                      "B" : [3,6,9,np.nan,15],
                      "C" : [2,5,np.nan,11,np.nan]})

In [3]:
imputer = SimpleImputer()

In [4]:
imputer.fit(my_df)

SimpleImputer()

In [5]:
imputer.transform(my_df)

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [8]:
my_df1 = imputer.transform(my_df)
my_df1

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [7]:
#It will also work by adding it together fit and transform
imputer.fit_transform(my_df)

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [ ]:
#Use this method for only test data 

In [11]:
#If you want to work with the Data Frame instead of arrays
my_df2 = pd.DataFrame(imputer.fit_transform(my_df),columns = my_df.columns)
my_df2

,A,B,C
0,1.0,3.00,2.0
1,4.0,6.00,5.0
2,7.0,9.00,6.0
3,10.0,8.25,11.0
4,13.0,15.00,6.0


In [14]:
#Above we applied the imputation logic to all the columns, we may want to apply it to a selection of columns

imputer.fit_transform(my_df[["B"]]) #This will just follow instruction and not overwrite the result dataset
my_df["B"]= imputer.fit_transform(my_df[["B"]]) # This will ensure it overwrites overall result data
my_df


,A,B,C
0,1,3.00,2.0
1,4,6.00,5.0
2,7,9.00,NaN
3,10,8.25,11.0
4,13,15.00,NaN
