In [1]:
#Importing Required libraries
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

In [2]:
my_df = pd.DataFrame({"A": [1,2,3,4,5],
                       "B": [1,1,3,3,4],
                       "C" :[1,2,9,np.nan,20]})

In [4]:
knn_imputer = KNNImputer()
knn_imputer.fit_transform(my_df)


array([[ 1.,  1.,  1.],
       [ 2.,  1.,  2.],
       [ 3.,  3.,  9.],
       [ 4.,  3.,  8.],
       [ 5.,  4., 20.]])

In [5]:
knn_imputer = KNNImputer(n_neighbors = 1) # Imputing values from the nearest neighbors
knn_imputer.fit_transform(my_df)

array([[ 1.,  1.,  1.],
       [ 2.,  1.,  2.],
       [ 3.,  3.,  9.],
       [ 4.,  3.,  9.],
       [ 5.,  4., 20.]])

In [6]:
knn_imputer =KNNImputer(n_neighbors =2) #Imputing values from the nearest 2 neighbors
knn_imputer.fit_transform(my_df)

array([[ 1. ,  1. ,  1. ],
       [ 2. ,  1. ,  2. ],
       [ 3. ,  3. ,  9. ],
       [ 4. ,  3. , 14.5],
       [ 5. ,  4. , 20. ]])

In [7]:
knn_imputer = KNNImputer(n_neighbors = 2, weights ="distance")
knn_imputer.fit_transform(my_df)

array([[ 1.        ,  1.        ,  1.        ],
       [ 2.        ,  1.        ,  2.        ],
       [ 3.        ,  3.        ,  9.        ],
       [ 4.        ,  3.        , 13.55634919],
       [ 5.        ,  4.        , 20.        ]])

In [10]:
my_df1 = pd.DataFrame(knn_imputer.fit_transform(my_df),columns=my_df.columns) # Instead of array, converting values in Dataframe
my_df1

,A,B,C
0,1.0,1.0,1.000000
1,2.0,1.0,2.000000
2,3.0,3.0,9.000000
3,4.0,3.0,13.556349
4,5.0,4.0,20.000000
